# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Timezone
timezone: Asia/Dhaka

# jekyll-seo-tag settings
title: Mian Al Ruhanyat # main title
tagline: SecureCoding | Springboot@Java # subtitle
description: >-
  A documentation vault for learning secure coding!

# Fill in the protocol & hostname for your site
url: "https://ruhanyat-994.github.io"

github:
  username: Ruhanyat-994

twitter:
  username: M_Ruhanyat

social:
  name: Mian Al Ruhanyat
  email: alruhanyat994@gmail.com
  links:
    - https://github.com/Ruhanyat-994
    - https://x.com/M_Ruhanyat
    - https://substack.com/@ruhanyat?
    - https://www.linkedin.com/in/alruhanyat/

# Site Verification Settings
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
  facebook: 

# Web Analytics Settings
analytics:
  google:
    id: 
  goatcounter:
    id: 
  umami:
    id: 
    domain: 
  matomo:
    id: 
    domain: 
  cloudflare:
    id: 
  fathom:
    id: 

# Page views settings
pageviews:
  provider: 

# Prefer color scheme
theme_mode: 

# CDN endpoint for media resources
cdn: 

# Avatar and social preview image
avatar: https://github.com/Ruhanyat-994/ruhanyat-994.github.io/blob/main/assets/Images/avater.jpg?raw=true
social_preview_image: 

# Table of Contents
toc: true

# Comments configuration
comments:
  provider: 
  disqus:
    shortname: 
  utterances:
    repo: 
    issue_term: 
  giscus:
    repo: 
    repo_id: 
    category: 
    category_id: 
    mapping: 
    strict: 
    input_position: 
    lang: 
    reactions_enabled: 

# Self-hosted static assets
assets:
  self_host:
    enabled: 
    env: 

# Progressive Web App (PWA)
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

# Pagination
paginate: 10

# Base URL
baseurl: ""

# Kramdown & syntax highlighting
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections
collections:
  tabs:
    output: true
    sort_by: order

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Sass
sass:
  style: compressed

# HTML compression
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Excluded files
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

# Jekyll archives
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
